kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-operators-placementrule
subjects:
- kind: ServiceAccount
  name: multicluster-operators-placementrule
  namespace: open-cluster-management
roleRef:
  kind: ClusterRole
  name: multicluster-operators-placementrule
  apiGroup: rbac.authorization.k8s.io
