apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-ready-clusters
  namespace: default
spec:
  clusterSelector: {}
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
