apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-ready-clusters
  namespace: default
spec:
  clusterSelector: {}
  # Only one cluster will be chosen from all matching clusters
  ClusterReplicas: 1
