apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-ready-clusters
  namespace: default
spec:
  clusters:
  - name: cluster1
  - name: cluster2
  # Only one cluster will be chosen from all matching clusters
  ClusterReplicas: 1
