apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: all-ready-clusters
  namespace: default
spec:
  clusterSelector: {}
  # This placement will be ignored by the default controller
  SchedulerName: my-scheduler
